---
version: '3.7'

services:
  app:
    build: .
    container_name: football_events_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
  app-consumer:
    build: .
    container_name: football_events_consumer_app
    volumes:
      - .:/app
    working_dir: /app
    command: php bin/console.php consumer:events
  redis:
    image: "redis:alpine"
    container_name: football_events_redis
    ports:
      - "6379:6379"
