---
version: '3.7'

services:
  app:
    build: .
    container_name: football_events_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
  redis:
    image: "redis:alpine"
    container_name: football_events_redis
    ports:
      - "6379:6379"
